// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Commands():Promise<Array<main.Command>>;

export function ToUpper(arg1:string):Promise<string>;
