// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Commands():Promise<Array<main.Command>>;

export function RunCommand(arg1:string,arg2:main.Command):Promise<string>;
